description: Contains a tool dependency definition that downloads and compiles version
  0.14 of the the scipy python library.
long_description: 'SciPy is open-source software for mathematics, science, and engineering.
  The SciPy library is built to work with NumPy arrays, and provides many user-friendly
  and efficient numerical routines such as routines for numerical integration and
  optimization.


  http://www.scipy.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/galaxyproject/tools-iuc'
name: package_scipy_0_14
owner: iuc
type: tool_dependency_definition
