# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_snpeff_4_1
owner: iuc
name: package_snpeff_4_1
type: tool_dependency_definition
description: Contains a tool dependency definition that installs version 4.1 SnpEff,
  a variant annotation and effect prediction tool.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    SnpEff is a variant annotation and effect prediction tool by Pablo
    Cingolani. It annotates and predicts the effects of variants on genes (such
    as amino acid changes).

    http://snpeff.sourceforge.net/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
