# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_rnastar_2_40d
owner: iuc
name: package_rnastar_2_40d
type: tool_dependency_definition
description: STAR is an ultrafast universal RNA-seq aligner
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    STAR is an ultrafast universal RNA-seq aligner

    For details, please see STAR paper:
    A. Dobin et al, Bioinformatics 2012; doi: 10.1093/bioinformatics/bts635
    http://bioinformatics.oxfordjournals.org/content/29/1/15 

    https://github.com/alexdobin/STAR/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
