# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_rnashapes_2_1_6
owner: iuc
name: package_rnashapes_2_1_6
type: tool_dependency_definition
description: Provides RNAshape 2.1.6
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    RNAshape abstraction maps structures to a tree-like domain of shapes,
    retaining adjacency and nesting of structural features, but disregarding
    helix lengths. Shape abstraction integrates well with dynamic programming
    algorithms, and hence it can be applied during structure prediction rather
    than afterwards. This avoids exponential explosion and can still give us a
    non-heuristic and complete account of properties of the molecule's folding
    space.

    http://bibiserv.techfak.uni-bielefeld.de/rnashapes
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
