description: Contains a tool dependency definition that downloads and compiles version
  0.15.x of the the scikit-learn package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'Easy-to-use and general-purpose machine learning in Python


  Scikit-learn integrates machine learning algorithms in the tightly-knit scientific
  Python world, building upon numpy, scipy, and matplotlib. As a machine-learning
  module, it provides versatile tools for data mining and analysis in any field of
  science and engineering. It strives to be simple and efficient, accessible to everybody,
  and reusable in various contexts.


  http://scikit-learn.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/galaxyproject/tools-iuc'
name: package_scikit_learn_0_15
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
