description: Contains a tool dependency definition that downloads and compiles version
  0.12 of the the scipy python library.
long_description: "SciPy is open-source software for mathematics, science, and engineering.\
  \ The SciPy library is built to work with NumPy arrays, and provides many user-friendly\
  \ and efficient numerical routines such as routines for numerical integration and\
  \ optimization.\r\n\r\nhttp://www.scipy.org/\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_scipy_0_12
owner: iuc
type: tool_dependency_definition
