# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_scikit_learn_0_13_with_atlas
owner: iuc
name: package_scikit_learn_0_13_with_atlas
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  0.13.x of the the scikit-learn package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Easy-to-use and general-purpose machine learning in Python Scikit-learn
    integrates machine learning algorithms in the tightly-knit scientific
    Python world, building upon numpy, scipy, and matplotlib. As a
    machine-learning module, it provides versatile tools for data mining and
    analysis in any field of science and engineering. It strives to be simple
    and efficient, accessible to everybody, and reusable in various contexts.

    http://scikit-learn.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
