description: Contains a tool dependency definition that downloads and compiles a version
  from 11-08-2014 of the vt tool.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'vt is a variant tool set that discovers short variants from Next
  Generation Sequencing data.

  http://genome.sph.umich.edu/wiki/Vt

  https://github.com/atks/vt


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools/

  '
name: package_vt_5c735ab14b5603d9f14da6ee0e63d86ba3779934
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
