categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  9.07 of the the ghostscript package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Ghostscript is a package of software that provides:\r\n\r\n- An\
  \ interpreter for the PostScript (TM) language, with the ability to convert PostScript\
  \ language files to many raster formats, view them on displays, and print them on\
  \ printers that don't have PostScript language capability built in;\r\n- An interpreter\
  \ for Portable Document Format (PDF) files, with the same abilities;\r\n- The ability\
  \ to convert PostScript language files to PDF (with some limitations) and vice versa;\
  \ and\r\n- A set of C procedures (the Ghostscript library) that implement the graphics\
  \ and filtering (data compression / decompression / conversion) capabilities that\
  \ appear as primitive operations in the PostScript language and in PDF.\r\n\r\n\
  http://www.ghostscript.com/\r\n\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\n\
  Repository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_ghostscript_9_07
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
