description: ghostscript_9_07
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: ''
name: package_ghostscript_9_07
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
