categories:
- Sequence Analysis
description: seqtk
long_description: |
  Sequence Analysis toolkit provies several small utilities for working with FastA and FastQ data.
name: seqtk
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/seqtk
type: unrestricted
