description: toolkit for processing FASTA and FASTQ files.
long_description: "Seqtk is a fast and lightweight tool for processing sequences in\
  \ the FASTA or FASTQ format. It seamlessly parses both FASTA and FASTQ files which\
  \ can also be optionally compressed by gzip.\r\nhttps://github.com/lh3/seqtk/\r\n\
  \r\nRepository-Maintainer: Eric Rasche\r\nRepository-Development: https://github.com/galaxy-iuc/tool_shed"
name: seqtk
owner: iuc
type: unrestricted
