categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.9 of the Python library ez-setup.
long_description: ''
name: package_ez_setup_0_9
owner: iuc
remote_repository_url: ''
type: tool_dependency_definition
