description: Contains a tool dependency definition that downloads and installs version 4.10.0 of the MEME suite
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The MEME Suite provides a unified set of tools for discovery and analysis of sequence motifs representing features such as DNA binding sites and protein interaction domains. \r\n\r\nhttp://nar.oxfordjournals.org/content/37/suppl_2/W202\
\ \r\n\r\nRepository-Maintainer: Intergalactic Utilities Commission \r\nRepository-Development: https://github.com/galaxyproject/tools-iuc/tree/master/package/package_meme_4_10_0"
owner: iuc
name: package_meme_4_10_0
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition