categories:
- Data Source
description: NCBI Entrez E-Utilties allow fetching data from NCBI Databases
long_description: |
  Entrez E-Utils provide an interface to the NCBI databases to allow querying
  and downloading datasets from NCBI

  http://www.ncbi.nlm.nih.gov/books/NBK25501/
name: ncbi_entrez_eutils
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/ncbi_entrez_eutils
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id  }}"
  description_template: "Wrapper for NCBI application {{ tool_name  }}"
suite:
  name: "suite_ncbi_entrez"
  description: NCBI Entrez E-Utilties allow fetching data from NCBI Databases

