categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.6 of the htseq package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "HTSeq: Analysing high-throughput sequencing data with Python\r\n\
  \r\nhttp://www-huber.embl.de/users/anders/HTSeq\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_htseq_0_6
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
