description: Contains a tool dependency definition that downloads and compiles version
  0.6 of the htseq package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'HTSeq: Analysing high-throughput sequencing data with Python


  http://www-huber.embl.de/users/anders/HTSeq


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_htseq_0_6
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
