description: Contains a tool dependency definition that downloads and compiles version
  3.4 of the the Linear Algebra PACKage.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Lapack provides routines for solving systems of simultaneous linear\
  \ equations, least-squares solutions of linear systems of equations, eigenvalue\
  \ problems, and singular value problems. \r\n\r\nhttp://www.netlib.org\r\n\r\nYou\
  \ need a Fortran 90 compiler, e.g. gfortran, to build that package.\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_lapack_3_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
