categories:
- Tool Dependency Packages
description: Linear Algebra PACKage
long_description: |
  Lapack provides routines for solving systems of simultaneous linear
  equations, least-squares solutions of linear systems of equations, eigenvalue problems,
  and singular value problems.
name: package_lapack_3_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
