description: Contains a tool dependency definition that downloads and compiles version
  0.7.7 of pysam.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Pysam is a python module for reading and manipulating Samfiles.\
  \ It's a lightweight wrapper of the samtools C-API.\r\n\r\nhttp://code.google.com/p/pysam/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening \r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_pysam_0_7_7
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
