description: Contains a tool dependency definition that downloads and compiles version
  5.0.5 of XZ Utils.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "XZ Utils is free general-purpose data compression software with\
  \ high compression ratio. XZ Utils were written for POSIX-like systems, but also\
  \ work on some not-so-POSIX systems. XZ Utils are the successor to LZMA Utils. \n\
  \nhttp://tukaani.org/xz/\n\nRepository-Maintainer: Bjoern Gruening\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools"
name: package_xz_5_0_5
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
