description: Installs the RHmm CRAN library.
long_description: 'Discrete, univariate or multivariate gaussian, mixture of univariate
  or multivariate gaussian HMM functions for simulation and estimation. '
name: package_rhmm_1_5_0
owner: iuc
type: tool_dependency_definition
