owner: iuc
name: package_rhmm_1_5_0
description: Installs the RHmm CRAN library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Discrete, univariate or multivariate gaussian, mixture of univariate or
    multivariate gaussian HMM functions for simulation and estimation.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
