description: Contains a tool dependency definition that installs version 3.4 SnpEff,
  a variant annotation and effect prediction tool.
long_description: "SnpEff is a variant annotation and effect prediction tool by Pablo\
  \ Cingolani.\r\nIt annotates and predicts the effects of variants on genes (such\
  \ as amino acid changes).\r\nSnpEff and SnpSift ( http://snpeff.sourceforge.net/\
  \ )"
name: package_snpeff_3_4
owner: iuc
type: tool_dependency_definition
