owner: iuc
name: package_snpeff_3_4
description: Contains a tool dependency definition that installs version 3.4 SnpEff,
  a variant annotation and effect prediction tool.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    SnpEff is a variant annotation and effect prediction tool by Pablo
    Cingolani. It annotates and predicts the effects of variants on genes (such
    as amino acid changes).

    http://snpeff.sourceforge.net/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
