categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.1.3 of grabix.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "grabix leverages the fantastic BGZF library in samtools to provide\
  \ random access into text files that have been compressed with bgzip. grabix creates\
  \ it's own index (.gbi) of the bgzipped file. Once indexed, one can extract arbitrary\
  \ lines from the file with the grab command.\r\n\r\nhttps://github.com/arq5x/grabix\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/\r\
  \n"
name: package_grabix_0_1_3
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
