description: Contains a tool dependency definition that downloads and compiles version
  1.1.x of the the chemfp package.
long_description: "Chemfp provides toolkit independent generation of fingerprints\
  \ and high-performance similarity search. The tools support the FPS fingerprint\
  \ file format.\r\n\r\nhttp://chemfp.com/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies\r\
  \n"
name: package_chemfp_1_1
owner: iuc
type: tool_dependency_definition
