owner: iuc
name: package_chemfp_1_1
description: Contains a tool dependency definition that downloads and compiles version
  1.1.x of the the chemfp package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Chemfp provides toolkit independent generation of fingerprints
    and high-performance similarity search. The tools support the FPS fingerprint
    file format.

    http://chemfp.com/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
