categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that installs version 1.835 of DB File.
long_description: |
   DB_File - Perl5 access to Berkeley DB version 1.x

   https://metacpan.org/pod/DB_File
name: package_perl_db_file_1_835
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_perl_db_file_1_835
type: tool_dependency_definition
