description: Contains a tool dependency definition that downloads and compiles version
  0.20.1 of cython.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Cython is an optimising static compiler for both the Python programming\
  \ language and the extended Cython programming language (based on Pyrex). It makes\
  \ writing C extensions for Python as easy as Python itself. \n\nhttp://cython.org\n\
  \nRepository-Maintainer: Bjoern Gruening\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_cython_0_20_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
