description: Contains a tool dependency definition that downloads and compiles version
  1.11 of gdbm.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: ' GNU dbm (or GDBM, for short) is a library of database functions
  that use extensible hashing and work similar to the standard UNIX dbm. These routines
  are provided to a programmer needing to create and manipulate a hashed database.


  http://www.gnu.org.ua/software/gdbm/gdbm.html


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_gdbm_1_11
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
