description: Contains a tool dependency definition that downloads and compiles version
  1.16 of gsl.
long_description: 'The GNU Scientific Library (GSL) is a numerical library for C and
  C++ programmers.

  The library provides a wide range of mathematical routines such as random number
  generators, special functions and least-squares fitting. There are over 1000 functions
  in total with an extensive test suite.


  http://www.gnu.org/software/gsl/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_gsl_1_16
owner: iuc
type: tool_dependency_definition
