categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.0 of randfold.
homepage_url: https://github.com/bgruening/galaxytools
long_description: "This is RANDFOLD version 2. The software compute the probability\
  \ that, for a \r\ngiven sequence, the Minimum Free Energy (MFE) of the secondary\
  \ structure is \r\ndifferent from MFE computed with random sequences. \r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening & Cameron Smith\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_randfold_2_0
owner: iuc
remote_repository_url: https://github.com/bgruening/galaxytools
type: tool_dependency_definition
