description: Contains a tool dependency definition that downloads and compiles version
  2.0 of randfold.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "This is RANDFOLD version 2. The software compute the probability\
  \ that, for a \ngiven sequence, the Minimum Free Energy (MFE) of the secondary structure\
  \ is \ndifferent from MFE computed with random sequences. \n\nRepository-Maintainer:\
  \ Bjoern Gruening & Cameron Smith\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_randfold_2_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
