categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.8.2 of the the weblogo package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "WebLogo is application designed to make the generation of sequence\
  \ logos as easy and painless as possible. \r\n\r\nhttp://weblogo.berkeley.edu/\r\
  \n\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_weblogo_2_8_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
