description: Contains a tool dependency definition that downloads and compiles version
  1.0 of openssl.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The OpenSSL Project is a collaborative effort to develop a robust,\
  \ commercial-grade, full-featured, and Open Source toolkit implementing the Secure\
  \ Sockets Layer (SSL v2/v3) and Transport Layer Security (TLS v1) protocols as well\
  \ as a full-strength general purpose cryptography library. \nThe project is managed\
  \ by a worldwide community of volunteers that use the Internet to communicate, plan,\
  \ and develop the OpenSSL toolkit and its related documentation. \n\nhttps://www.openssl.org/\n\
  \nRepository-Maintainer: Bjoern Gruening\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_openssl_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
