description: MinCED - Mining CRISPRs in Environmental Datasets
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "MinCED is a program to find Clustered Regularly Interspaced Short\
  \ Palindromic\r\nRepeats (CRISPRs) in full genomes or environmental datasets such\
  \ as metagenomes,\r\nin which sequence size can be anywhere from 100 to 800 bp.\
  \ MinCED runs from the\r\ncommand-line and was derived from CRT (http://www.room220.com/crt/):\r\
  \n  Charles Bland et al., CRISPR Recognition Tool (CRT): a tool for automatic\r\n\
  \  detection of clustered regularly interspaced palindromic repeats, BMC\r\n  Bioinformatics\
  \ 8, no. 1 (2007): 209.\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools/"
name: package_minced_0_1_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
