description: ' Contains a tool dependency definition that downloads and compiles version
  2.3.2 of the Open Babel package '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Open Babel is a chemical toolbox designed to speak the many languages\
  \ of chemical data. It's an open, collaborative project allowing anyone to search,\
  \ convert, analyze, or store data from molecular modeling, chemistry, solid-state\
  \ materials, biochemistry, or related areas.\r\n\r\nhttp://openbabel.org\r\n\r\n\
  Repository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies\r\
  \n"
name: package_openbabel_2_3
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
