description: 'Contains a tool dependency definition that downloads and compiles version
  2.1 of the Vienna RNA package. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'The Vienna RNA Package consists of a C code library and several
  stand-alone programs for the prediction and comparison of RNA secondary structures.


  http://www.tbi.univie.ac.at/RNA/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_vienna_rna_2_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
