description: Contains a tool dependency definition that downloads and compiles version
  3.0 of libffi.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'Libffi are compilers for high level languages generate code that
  follows certain conventions.


  http://sourceware.org/libffi/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_libffi_3_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
