# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_tpp_4_7_0
owner: iuc
name: package_tpp_4_7_0
description: Downloads and compiles version 4.7.0 of the Trans-Proteomic Pipeline.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    The Trans-Proteomic Pipeline (TPP) is a collection of integrated tools for
    MS/MS proteomics, developed at the SPC. 
    
    http://tools.proteomecenter.org
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
