description: Contains a tool dependency definition that downloads and compiles version
  2.0 of ruby.
long_description: "This installs ruby 2.0.x. Ruby is a dynamic, open source programming\
  \ language with a focus on simplicity and productivity. \r\nIt has an elegant syntax\
  \ that is natural to read and easy to write.\r\nhttps://www.ruby-lang.org/\r\n\r\
  \nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_ruby_2_0
owner: iuc
type: tool_dependency_definition
