description: Contains a tool dependency definition that downloads and compiles version
  2.1.0 of the expat library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'Expat is an XML parser library written in C. It is a stream-oriented
  parser in which an application registers handlers for things the parser might find
  in the XML document (like start tags).


  http://expat.sourceforge.net/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_expat_2_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
