description: ' Contains a tool dependency definition that downloads and compiles version
  4.1.0 of the GNU awk. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The awk utility interprets a special-purpose programming language\
  \ that makes it possible to handle simple data-reformatting jobs with just a few\
  \ lines of code. \r\n\r\nhttp://www.gnu.org/software/gawk/\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/"
name: package_gnu_awk_4_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
