categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads version
  0.42.4 of Kallisto
long_description: |
  Kallisto is a program for quantifying abundances of transcripts from RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.

  https://pachterlab.github.io/kallisto/
homepage_url: https://pachterlab.github.io/kallisto/
name: package_kallisto_0_42_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_kallisto_0_42_4
type: tool_dependency_definition
