categories:
- Tool Dependency Packages
description: Provides BioRuby 1.4
name: package_ruby2_bioruby_1_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
