# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_ruby2_bioruby_1_4
owner: iuc
name: package_ruby2_bioruby_1_4
type: tool_dependency_definition
description: Provides BioRuby 1.4
homepage_url: https://github.com/galaxyproject/tools-iuc/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
