categories:
- Next Gen Mappers
description: 'rna STAR 2.0.3e '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "WARNING: This will eat all your cluster node RAM and then some.\r\
  \nhg19 uses about 30GB but it's really fast. See http://gettinggeneticsdone.blogspot.com.au/2012/11/star-ultrafast-universal-rna-seq-aligner.html\
  \ eg\r\nYou also need a new set of genome indexes. Sigh. So you have to build those\
  \ yourself until I figure out how to make an index manager.\r\nMost of this wrapper\
  \ was originally written by Jeremy Goecks, with kibbitzing and automated dependency\
  \ installation by Ross Lazarus."
name: rgrnastar_203e
owner: fubar
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
