categories:
- Data Managers
description: Data Manager for building Sailfish indexes
long_description: |
  Sailfish is a tool for transcript quantification from RNA-seq data. It requires a set of target transcripts
  (either from a reference or de-novo assembly) to quantify. All you need to run sailfish is a fasta file containing your reference
  transcripts and a (set of) fasta/fastq file(s) containing your reads. Sailfish runs in two phases; indexing and quantification.
  The indexing step is independent of the reads, and only needs to be run once for a particular set of reference transcripts and
  choice of k (the k-mer size). The quantification step, obviously, is specific to the set of RNA-seq reads and is thus run more frequently
  Additional covariates may optionally be provided to further inform the peak-calling process.
homepage_url: https://github.com/kingsfordgroup/sailfish
name: data_manager_sailfish_index_builder
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_sailfish_index_builder
type: unrestricted
