categories:
  - Data Source
description: IRIS-TCGA Data source tool
long_description: |
  Retrieve data from IRIS-TCGA
name: data_source_iris_tcga
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/data_source_iris_tcga
