description: snpEff SnpSift dbnsfp tool that can use any dbnsfp-like annotation data
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Annotates variants on genes using a tabular set of annotation values\
  \ such as those from the dbNSFP, an integrated database of human functional predictions\
  \ from multiple algorithms (SIFT, Polyphen2, LRT and MutationTaster, PhyloP and\
  \ GERP++, etc.)\r\n\r\nThis tool determines the available annotations from the input,\
  \ so it can be used for other organisms other than human or other annotation values\
  \ than available from dbNSFP.\r\nhttp://snpeff.sourceforge.net/SnpSift.html#dbNSFP\
  \ \r\n\r\nSnpEff and SnpSift are developed by Pablo Cingolani at http://snpeff.sourceforge.net/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening, Jim Johnson, Nicola Soranzo\r\nRepository-Development:\
  \ https://github.com/galaxy-iuc/tool_shed/"
name: snpsift_dbnsfp_generic
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
