name: package_numpy_1_7_with_atlas
owner: iuc
categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.7 of the the python numpy package with Atlas
long_description: |
  NumPy is the fundamental package for scientific computing with
  Python.

  www.numpy.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
