owner: iuc
name: package_rdkit_2013_03
description: Contains a tool dependency definition that downloads and compiles version
  2013-03 of the RDKit cheminformatics and machine-learning package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    A collection of cheminformatics and machine-learning software written in
    C++ and Python.

    The core algorithms and data structures are written in C++. Wrappers are
    provided to use the toolkit from either Python or Java.

    Additionally, the RDKit distribution includes a PostgreSQL-based cartridge
    that allows molecules to be stored in relational database and retrieved via
    substructure and similarity searches.

    http://www.rdkit.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
