categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads, compiles and extracts
  version 3.1.x of the the eigen template library.
long_description: 'Eigen is a C++ template library for linear algebra: matrices, vectors,
  numerical solvers, and related algorithms.

  '
name: package_eigen_3_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
