categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.2.10 of DESeq2.
name: package_deseq2_1_2_10
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
