categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  35x1 of the the UCSC blat package.
long_description: |
  Blat is an alignment tool like BLAST, but it is structured differently.

  http://genome.ucsc.edu/FAQ/FAQblat.html
name: package_blat_35x1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
