description: ' Contains a tool dependency definition that downloads and compiles version
  35x1 of the the UCSC blat package. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Blat is an alignment tool like BLAST, but it is structured differently.\r\
  \n\r\nhttp://genome.ucsc.edu/FAQ/FAQblat.html\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_blat_35x1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
