categories:
  - Metagenomics
description: Rarefaction via Vegan R package
long_description: |
  Gives the expected species richness in random subsamples of size sample from the community.
  Draws rarefaction curves.

  http://cran.r-project.org/web/packages/vegan/index.html
name: vegan_rarefaction
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/vegan_rarefaction
