categories:
- Tool Dependency Packages
description: package providing GraphClust 0.7.6
long_description: 'GraphClust is software for alignment-free structural clustering
  of local

  RNA secondary structures.

  http://www.bioinf.uni-freiburg.de/Software/GraphClust/

  doi:10.1093/bioinformatics/bts224

  '
name: package_graphclust_0_7_6
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
