# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_graphclust_0_7_6
owner: iuc
name: package_graphclust_0_7_6
type: tool_dependency_definition
description: package providing GraphClust 0.7.6
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    GraphClust is software for alignment-free structural clustering of local
    RNA secondary structures.

    http://www.bioinf.uni-freiburg.de/Software/GraphClust/
    doi:10.1093/bioinformatics/bts224
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
