categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  5.18.x of the the perl language.
long_description: ''
name: package_perl_5_18
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
