description: Contains a tool dependency definition that downloads and compiles version
  5.18.x of the the perl language.
long_description: "Galaxy wrappers for common unix text-processing tools\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/galaxyproject/tools-iuc"
name: package_perl_5_18
owner: iuc
type: tool_dependency_definition
