categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  5.18.x of the the perl language.
name: package_perl_5_18
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_perl_5_18
type: tool_dependency_definition
