categories:
- Tool Dependency Packages
description: ' Contains a tool dependency definition that downloads and compiles version
  1.8 of the Vienna RNA package. '
homepage_url: https://github.com/bgruening/galaxytools
long_description: "The Vienna RNA Package consists of a C code library and several\
  \ stand-alone programs for the prediction and comparison of RNA secondary structures.\r\
  \n\r\nhttp://www.tbi.univie.ac.at/RNA/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_vienna_rna_1_8
owner: iuc
remote_repository_url: https://github.com/bgruening/galaxytools
type: tool_dependency_definition
