description: ' Contains a tool dependency definition that downloads and compiles version
  1.8 of the Vienna RNA package. '
long_description: 'The Vienna RNA Package consists of a C code library and several
  stand-alone programs for the prediction and comparison of RNA secondary structures.


  http://www.tbi.univie.ac.at/RNA/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_vienna_rna_1_8
owner: iuc
type: tool_dependency_definition
