categories:
- Tool Dependency Packages
description: |
  CCAT is a software package for the analysis of ChIP-seq data with negative control.
name: package_ccat_3_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
