# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_ccat_3_0
owner: iuc
name: package_ccat_3_0
type: tool_dependency_definition
description: |
    CCAT is a software package for the analysis of ChIP-seq data with negative
    control.
homepage_url: https://github.com/galaxyproject/tools-iuc/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
