description: Contains a tool dependency definition that downloads and compiles version
  1.41 of the Ontology toolkit written in perl.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "ONTO-PERL a collection of PERL modules for dealing with OBO-formatted\r\
  \nontologies (like the Gene Ontology). This code distribution gathers \r\nobject-oriented\
  \ modules (for dealing with ontology elements such as \r\nTerm, Relationship and\
  \ so forth), scripts (for typical tasks such as \r\nformat conversions: obo2owl,\
  \ owl2obo; besides, there are also many \r\nexamples that can be easily adapted\
  \ for specific applications), and a \r\nset of test files to ensure the suite's\
  \ implementation quality.\r\n\r\nhttp://search.cpan.org/dist/ONTO-PERL/\r\n\r\n\
  Repository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_onto_perl_1_41
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
