# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_r_3_0_1_with_atlas
owner: iuc
name: package_r_3_0_1_with_atlas
type: tool_dependency_definition
description: R version 3.0.1 with Atlas support
homepage_url: https://github.com/galaxyproject/tools-iuc/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
