owner: iuc
name: snpsift_dbnsfp
description: snpEff SnpSift dbnsfp tool from Pablo Cingolani
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Annotates variants on genes using the dbNSFP, an integrated database of
    human functional predictions from multiple algorithms (SIFT, Polyphen2, LRT
    and MutationTaster, PhyloP and GERP++, etc.)
    http://snpeff.sourceforge.net/SnpSift.html#dbNSFP

    SnpEff and SnpSift are developed by Pablo Cingolani.

    http://snpeff.sourceforge.net/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
categories:
- Variant Analysis
