description: snpEff SnpSift dbnsfp tool from Pablo Cingolani
long_description: "Annotates variants on genes using the dbNSFP, an integrated database\
  \ of human functional predictions from multiple algorithms (SIFT, Polyphen2, LRT\
  \ and MutationTaster, PhyloP and GERP++, etc.)\r\nhttp://snpeff.sourceforge.net/SnpSift.html#dbNSFP\
  \ \r\nSnpEff and SnpSift are developed by Pablo Cingolani at http://snpeff.sourceforge.net/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening, Jim Johnson, Nicola Soranzo\r\nRepository-Development:\
  \ https://github.com/galaxy-iuc/tool_shed/"
name: snpsift_dbnsfp
owner: iuc
type: unrestricted
