description: Contains a tool dependency definition that downloads and compiles version
  3.10 of the the Automatically Tuned Linear Algebra Software.
long_description: "The ATLAS (Automatically Tuned Linear Algebra Software) project\
  \ is an ongoing research effort focusing on applying empirical techniques in order\
  \ to provide portable performance. At present, it provides C and Fortran77 interfaces\
  \ to a portably efficient BLAS implementation, as well as a few routines from LAPACK.\r\
  \n\r\nhttp://math-atlas.sourceforge.net/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_atlas_3_10
owner: iuc
type: tool_dependency_definition
