categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.4 of Python.
long_description: ''
name: package_python_3_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
