description: Contains a tool dependency definition that downloads and compiles version
  0.13.x of the the scikit-learn package.
long_description: "Easy-to-use and general-purpose machine learning in Python\r\n\r\
  \nScikit-learn integrates machine learning algorithms in the tightly-knit scientific\
  \ Python world, building upon numpy, scipy, and matplotlib. As a machine-learning\
  \ module, it provides versatile tools for data mining and analysis in any field\
  \ of science and engineering. It strives to be simple and efficient, accessible\
  \ to everybody, and reusable in various contexts.\r\n\r\nhttp://scikit-learn.org/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_scikit_learn_0_13
owner: iuc
type: tool_dependency_definition
