# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_segemehl_0_1_6
owner: iuc
name: package_segemehl_0_1_6
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  0.16.x of the the segemehl package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    segemehl is a software to map short sequencer reads to reference genomes.
    Unlike other methods, segemehl is able to detect not only mismatches but
    also insertions and deletions. Furthermore, segemehl is not limited to a
    specific read length and is able to mapprimer- or polyadenylation
    contaminated reads correctly. segemehl implements a matching strategy based
    on enhanced suffix arrays (ESA). Segemehl now supports the SAM format,
    reads gziped queries to save both disk and memory space and allows
    bisulfite sequencing mapping and split read mapping.

    http://www.bioinf.uni-leipzig.de/Software/segemehl/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
