categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and extract version
  1.3.1 of tRNAscan-SE.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "tRNAscan-SE: a program for improved detection of transfer RNA genes\
  \ in genomic sequence.\r\n\r\nhttp://www.ncbi.nlm.nih.gov/pubmed/9023104\r\n\r\n\
  Repository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_trnascan_1_3_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
