description: Contains a tool dependency definition that downloads and compiles version
  8.22 of the GNU coreutils.
long_description: "The GNU Core Utilities are the basic file, shell and text manipulation\
  \ utilities of the GNU operating system.\nThese are the core utilities which are\
  \ expected to exist on every operating system. \n\nhttp://www.gnu.org/software/coreutils/\n\
  \nRepository-Maintainer: Bjoern Gruening\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_gnu_coreutils_8_22
owner: iuc
type: tool_dependency_definition
