categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  8.22 of the GNU coreutils.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The GNU Core Utilities are the basic file, shell and text manipulation\
  \ utilities of the GNU operating system.\r\nThese are the core utilities which are\
  \ expected to exist on every operating system. \r\n\r\nhttp://www.gnu.org/software/coreutils/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_gnu_coreutils_8_22
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
