description: Contains a tool dependency definition that downloads and compiles version
  0.7.5 of pysam.
long_description: "Pysam is a python module for reading and manipulating Samfiles.\
  \ It's a lightweight wrapper of the samtools C-API.\r\n\r\nhttp://code.google.com/p/pysam/"
name: package_pysam_0_7_5
owner: iuc
type: tool_dependency_definition
