categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.4 of the the GNU libtool package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "GNU Libtool - The GNU Portable Library Tool\r\n\r\nhttp://www.gnu.org/software/libtool/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies\r\
  \n"
name: package_libtool_2_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
