categories: [Sequence Analysis]
description:  DGPI PredSi  Tmseg
long_description: 
  "\nDGPI Detection/prediction of GPI cleavage\
  \ site  in a protein\n
  PredSi: PREDIction of SIgnal peptides\nhttp://www.predisi.de/\n
  TMSEG\
  \ predicts transmembrane proteins (TMP) and transmembrane helices (TMH) using position-specific\
  \ scoring matrices (PSSM) \nhttps://rostlab.org/owiki/index.php/Tmseg"
name: protein_annotation
owner: iuc
remote_repository_url: 'https://github.com/iuc/tools-iuc/tools/protein_annotation/  '
