categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  7.35 of libcurl.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "libcurl is a free and easy-to-use client-side URL transfer library,\
  \ supporting DICT, FILE, FTP, FTPS, Gopher, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS,\
  \ POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, Telnet and TFTP. libcurl supports\
  \ SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP form based upload,\
  \ proxies, cookies, user+password authentication (Basic, Digest, NTLM, Negotiate,\
  \ Kerberos), file transfer resume, http proxy tunneling and more! \r\n\r\nhttp://curl.haxx.se/libcurl/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_libcurl_7_35
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
