description: snpEff SnpSift genesets tool from Pablo Cingolani
long_description: "Annotates variants with GeneSets, such as Gene Ontology (GO), KEGG,\
  \ Reactome, etc.; \r\nhttp://snpeff.sourceforge.net/SnpSift.html#geneSets \r\nSnpEff\
  \ and SnpSift are developed by Pablo Cingolani at http://snpeff.sourceforge.net/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening, Jim Johnson, Nicola Soranzo\r\nRepository-Development:\
  \ https://github.com/galaxy-iuc/tool_shed/"
name: snpsift_genesets
owner: iuc
type: unrestricted
