owner: iuc
name: snpsift_dbnsfp
description: snpEff SnpSift dbnsfp tool from Pablo Cingolani
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Annotates variants with GeneSets, such as Gene Ontology (GO), KEGG,
    Reactome, etc.; http://snpeff.sourceforge.net/SnpSift.html#geneSets 

    SnpEff and SnpSift are developed by Pablo Cingolani.

    http://snpeff.sourceforge.net/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
categories:
- Variant Analysis
