categories:
- Tool Dependency Packages
description: Fido is a method for protein identification in MS/MS proteomics
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Fido is a free software tool used in the area of computational\
  \ proteomics. It calculates posterior probabilities for protein identifications\
  \ based on database searches of tandem mass spectra. \r\n\r\nhttp://noble.gs.washington.edu/proj/fido/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/galaxyproject/tools-iuc"
name: package_fido_f63cd47b8414f87d57b8c1b713d34a04b29c7aee
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
