categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  4.3 of netcdf.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "NetCDF (network Common Data Form) is a set of software libraries\
  \ and machine-independent data formats that support the creation, access, and sharing\
  \ of array-oriented scientific data.\r\n\r\nhttp://www.unidata.ucar.edu/downloads/netcdf/index.jsp\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_netcdf_4_3
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
