categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.2.5 of the python library suspenders.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Allows the merging of alignments that have been annotated using\
  \ pylapels into a single alignment that picks the highest quality alignment.\r\n\
  \r\nhttps://pypi.python.org/pypi/suspenders/\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/"
name: package_suspenders_0_2_5
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
