description: Contains a tool dependency definition that downloads and compiles version
  2.19 of bedtools.
long_description: 'bedtools - a swiss army knife for genome arithmetic


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools/'
name: package_bedtools_2_19
owner: iuc
type: tool_dependency_definition
