description: Contains a tool dependency definition that downloads and compiles version
  2.19 of bedtools.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'bedtools - a swiss army knife for genome arithmetic


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools/'
name: package_bedtools_2_19
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
