description: Contains a tool dependency definition that downloads and compiles version
  2012-12 of the RDKit cheminformatics and machine-learning package.
long_description: "A collection of cheminformatics and machine-learning software written\
  \ in C++ and Python.\r\n\r\nThe core algorithms and data structures are written\
  \ in C++. Wrappers are provided to use the toolkit from either Python or Java.\r\
  \n\r\nAdditionally, the RDKit distribution includes a PostgreSQL-based cartridge\
  \ that allows molecules to be stored in relational database and retrieved via substructure\
  \ and similarity searches.\r\nhttp://www.rdkit.org/\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_rdkit_2012_12
owner: iuc
type: tool_dependency_definition
