# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_msgfplus_20140210
owner: iuc
name: package_msgfplus_20140210
type: tool_dependency_definition
description: Provides MS-GF+ from 20140210
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
     MS-GF+ is a new MS/MS database search tool that is sensitive (it
     identifies more peptides than other database search tools and as many
     peptides as spectral library search tools) and universal (works well for
     diverse types of spectra, different configurations of MS instruments and
     different experimental protocols).

    http://proteomics.ucsd.edu/Software/MSGFPlus/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
