categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.7 of the the python numpy package
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "NumPy is the fundamental package for scientific computing with\
  \ Python.\r\n\r\nThis is the version 1.7 of numpy.\r\nwww.numpy.org/\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_numpy_1_7
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
