description: Contains a tool dependency definition that downloads and compiles version
  1.7 of the the python numpy package
long_description: "This repository is intended to be defined as a complex repository\
  \ dependency within a separate repository. http://wiki.galaxyproject.org/DefiningRepositoryDependencies#Complex_repository_dependencies:_tool_dependency_definitions_that_contain_repository_dependency_definitions\r\
  \n\r\nThis is the version 1.7 of numpy.\r\nwww.numpy.org/\r\n\r\nNumPy is the fundamental\
  \ package for scientific computing with Python.\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/galaxy-iuc/tool_shed/"
name: package_numpy_1_7
owner: iuc
type: tool_dependency_definition
