description: snpEff tools from Pablo Cingolani
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Variant annotation and effect prediction tools. It annotates and\
  \ predicts the effects of variants on genes. This repository should manage tool\
  \ dependencies. There are data managers for the Galaxy admin to download genome\
  \ databases. SnpEff is developed by Pablo Cingolani at http://snpeff.sourceforge.net/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening, Jim Johnson, Nicola Soranzo\r\nRepository-Development:\
  \ https://github.com/galaxy-iuc/tool_shed/"
name: snpeff
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
