description: Contains a tool dependency definition that downloads and compiles version
  1.2.x of the the python matplotlib package.
long_description: "matplotlib is a python 2D plotting library which produces publication\
  \ quality figures.\r\n\r\nThis is the version 1.2.x of matplotlib.\r\nwww.matplotlib.org/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_matplotlib_1_2
owner: iuc
type: tool_dependency_definition
