categories:
- Sequence Analysis
- Next Gen Mappers
description: Fast and accurate alignment of BS-seq reads.
long_description: |
    A fast and accurate aligner of BS-seq data.

    - Supports single-end and paired-end alignments
    - Supports gapped alignments
    - Faster and more sensitive than many other tools
name: bwameth
owner: dpryan79
remote_repository_url: https://github.com/dpryan79/tools-iuc/tools/bwameth
type: unrestricted
