description: Contains a tool dependency definition that downloads and compiles version
  1.3 of the the GraphicsMagick Image Processing System.
long_description: "GraphicsMagick is the swiss army knife of image processing and\
  \ it provides a robust and efficient collection of tools and libraries which support\
  \ reading, writing, and manipulating an image in over 88 major formats including\
  \ important formats like DPX, GIF, JPEG, JPEG-2000, PNG, PDF, PNM, and TIFF.\r\n\
  \r\nhttp://www.graphicsmagick.org\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_graphicsmagick_1_3
owner: iuc
type: tool_dependency_definition
