description: Contains a tool dependency definition that downloads and compiles version
  1.53 of the boost C++ libraries
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Boost provides free peer-reviewed portable C++ source libraries.\r\
  \n\r\nhttp://www.boost.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools"
name: package_boost_1_53
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
