categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.55 of the boost C++ libraries
homepage_url: https://github.com/bgruening/galaxytools
long_description: "Boost provides free peer-reviewed portable C++ source libraries.\r\
  \n\r\nhttp://www.boost.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools"
name: package_boost_1_55
owner: iuc
remote_repository_url: https://github.com/bgruening/galaxytools
type: tool_dependency_definition
