description: Contains a tool dependency definition that downloads and compiles version
  1.55 of the boost C++ libraries
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'Boost provides free peer-reviewed portable C++ source libraries.


  http://www.boost.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_boost_1_55
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
