description: Contains a tool dependency definition that downloads and compiles version
  1.55 of the boost C++ libraries
long_description: 'Boost provides free peer-reviewed portable C++ source libraries.


  http://www.boost.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_boost_1_55
owner: iuc
type: tool_dependency_definition
