description: Contains a tool dependency definition that downloads and extract version
  1.2.36 of Aragorn.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "ARAGORN, tRNA (and tmRNA) detection. \r\n\r\nhttp://www.ncbi.nlm.nih.gov/pubmed/14704338\
  \ \r\n\r\nRepository-Maintainer: Bjoern Gruening \r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_aragorn_1_2_36
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
