categories: [Sequence Analysis]
description: Merge gff using gffutils
long_description: Creates a gffutils SQLite database from predicted proteins gff and adds protein annotations from blastp protein matches in outfmt6, tmhmm, signalp and hmmer predictions
name: mergegffs
owner: iuc
