description: Contains a tool dependency definition that downloads and compiles version
  3.8.3 of SQLite.
long_description: 'SQLite is a software library that implements a self-contained,
  serverless, zero-configuration, transactional SQL database engine. SQLite is the
  most widely deployed SQL database engine in the world. The source code for SQLite
  is in the public domain.


  http://www.sqlite.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_sqlite_3_8_3
owner: iuc
type: tool_dependency_definition
