description: Contains a tool dependency definition that downloads and compiles version
  2.4 of the freetype font library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "FreeType is a freely available software library to render fonts.\r\
  \n\r\nIt is written in C, designed to be small, efficient, highly customizable,\
  \ and portable while capable of producing high-quality output (glyph images) of\
  \ most vector and bitmap font formats.\r\nhttp://www.freetype.org/\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_freetype_2_4
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
