# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_vienna_rna_2_1_5
owner: iuc
name: package_vienna_rna_2_1_5
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  2.1.5 of the Vienna RNA package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    The ViennaRNA Package consists of a C code library and several stand-alone
    programs for the prediction and comparison of RNA secondary structures. 

    http://www.tbi.univie.ac.at/RNA/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
