categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and compiles version 1.2.11 of flash
long_description: |
    FLASH, Fast Length Adjustment of SHort reads, is a very accurate fast tool to merge paired-end reads from fragments that are shorter than twice the length of reads. The extended length of reads has a significant positive impact on improvement of genome assemblies.
name: package_flash_1_2_11
owner: rjullien
type: tool_dependency_definition
