categories:
- Tool Dependency Packages
description: Installs version 0.20 of bwa-meth from github
long_description: |
  A fast and accurate aligner of BS-seq data.

    - Supports single-end and paired-end alignments
    - Supports gapped alignments
    - Faster and more sensitive than many other tools
name: package_python_2_7_bwameth_0_20
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_python_2_7_bwameth_0_20
type: tool_dependency_definition
