description: ' Contains a tool dependency definition that downloads and compiles version
  4.2.2 of the GNU sed + an addidtion sandbox feature. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "sed is a stream editor. A stream editor is used to perform basic\
  \ text transformations on an input stream (a file or input from a pipeline). While\
  \ in some ways similar to an editor which permits scripted edits (such as ed), sed\
  \ works by making only one pass over the input(s), and is consequently more efficient.\
  \ But it is sed's ability to filter text in a pipeline which particularly distinguishes\
  \ it from other types of editors. \r\n\r\nThis contains an additional patch developed\
  \ by Assaf Gordon that add a --sandbox feature to disables potentially harmful sed\
  \ functions, when used in Galaxy.\r\n\r\nhttp://www.gnu.org/software/sed/\r\n\r\n\
  Repository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_gnu_sed_4_2_2_sandbox
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
