categories:
- Tool Dependency Packages
description: ' Contains a tool dependency definition that downloads and compiles version
  1.0 of the SAMTools package. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "samtools - Utilities for the Sequence Alignment/Map (SAM) format\r\
  \n\r\nSamtools is a set of utilities that manipulate alignments in the BAM format.\
  \ It imports from and exports to the SAM (Sequence Alignment/Map) format, does sorting,\
  \ merging and indexing, and allows to retrieve reads in any regions swiftly.\r\n\
  \r\nSamtools is designed to work on a stream. It regards an input file '-' as the\
  \ standard input (stdin) and an output file '-' as the standard output (stdout).\
  \ Several commands can thus be combined with Unix pipes. Samtools always output\
  \ warning and error messages to the standard error output (stderr).\r\n\r\nSamtools\
  \ is also able to open a BAM (not SAM) file on a remote FTP or HTTP server if the\
  \ BAM file name starts with 'ftp://' or 'http://'. Samtools checks the current working\
  \ directory for the index file and will download the index upon absence. Samtools\
  \ does not retrieve the entire alignment file unless it is asked to do so.\r\n\r\
  \nhttp://www.htslib.org/man/samtools/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools "
name: package_samtools_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
