description: Contains a tool dependency definition that downloads and compiles version
  1.0 of the bzlib library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "bzip2 is a freely available, patent free, high-quality data compressor.\
  \ It typically compresses files to within 10X to 15X of the best available techniques\
  \ (the PPM family of statistical compressors), whilst being around twice as fast\
  \ at compression and six times faster at decompression.\r\n\r\nhttp://www.bzip.org\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_bzlib_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
