description: package_macs2_2_1_0
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: package_macs2_2_1_0
name: package_macs2_2_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
