# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_weka_3_7_11
owner: iuc
name: package_weka_3_7_11
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  3.7.11 of the Weka package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Weka is a collection of machine learning algorithms for data mining tasks.
    The algorithms can either be applied directly to a dataset or called from
    your own Java code. Weka contains tools for data pre-processing,
    classification, regression, clustering, association rules, and
    visualization. It is also well-suited for developing new machine learning
    schemes.

    http://www.cs.waikato.ac.nz/~ml/weka/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
