description: Contains a tool dependency definition that downloads and extract version
  6.2.x of the the GNU readline library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The GNU Readline library provides a set of functions for use by\
  \ applications that allow users to edit command lines as they are typed in. Both\
  \ Emacs and vi editing modes are available. The Readline library includes additional\
  \ functions to maintain a list of previously-entered command lines, to recall and\
  \ perhaps reedit those lines, and perform csh-like history expansion on previous\
  \ commands.\r\n\r\nwww.gnu.org/s/readline/\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_readline_6_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
