categories:
- Tool Dependency Packages
description: Git is a free and open source distributed version control system.
long_description: |
  Git is a free and open source distributed version control system
  designed to handle everything from small to very large projects with
  speed and efficiency.
  
  Git is easy to learn and has a tiny footprint with lightning fast
  performance. It outclasses SCM tools like Subversion, CVS, Perforce,
  and ClearCase with features like cheap local branching, convenient
  staging areas, and multiple workflows.
  
  https://git-scm.com/
name: package_git_2_4_6
owner: iuc
homepage_url: https://git-scm.com/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_git_2_4_6
type: tool_dependency_definition
