name: four_color_plot
owner: iuc
description: Contains a tool that produces a graphical representation of FASTA data with each nucleotide represented by a selected color.
homepage_url:
long_description: |
  Contains a tool that produces a graphical representation of FASTA data with each nucleotide represented by a selected color.
type: unrestricted
categories:
- Visualization
