description: Contains a tool dependency definition that downloads and compiles version
  1.9 of ruby.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "This installs ruby 1.9.3. Ruby is a dynamic, open source programming\
  \ language with a focus on simplicity and productivity. \r\nIt has an elegant syntax\
  \ that is natural to read and easy to write.\r\nhttps://www.ruby-lang.org/\r\n\r\
  \nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_ruby_1_9
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
