description: Contains a tool dependency definition that downloads and compiles version
  3.0.2 of the the R package.
long_description: "R is a free software environment for statistical computing and\
  \ graphics.\r\nhttp://www.r-project.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_r_3_0_2
owner: iuc
type: tool_dependency_definition
