categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles the
  Dezember 2013 version of bx-python.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The bx-python project is a python library and associated set of\
  \ scripts to allow for rapid implementation of genome scale analyses.\r\n\r\nhttps://bitbucket.org/james_taylor/bx-python\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening \r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_bx_python_12_2013
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
