categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.1.7 of the Python Imaging Library (PIL).
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The Python Imaging Library (PIL) adds image processing capabilities\
  \ to your Python interpreter. This library supports many file formats, and provides\
  \ powerful image processing and graphics capabilities.\r\n\r\nhttp://www.pythonware.com/products/pil/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_pil_1_1_7
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
