categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.1.0 of the GD library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "GD is an open source code library for the dynamic creation of images\
  \ by programmers. \r\nGD is written in C, and \"wrappers\" are available for Perl,\
  \ PHP and other languages. \r\nGD creates PNG, JPEG, GIF, WebP, XPM, BMP images,\
  \ among other formats. \r\nGD is commonly used to generate charts, graphics, thumbnails,\
  \ and most anything else, on the fly. \r\nWhile not restricted to use on the web,\
  \ the most common applications of GD involve website development.\r\n          \
  \  \r\nhttp://libgd.bitbucket.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/"
name: package_libgd_2_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
