description: Contains a tool dependency definition that downloads and compiles version
  2.1.0 of the GD library.
long_description: "GD is an open source code library for the dynamic creation of images\
  \ by programmers. \nGD is written in C, and \"wrappers\" are available for Perl,\
  \ PHP and other languages. \nGD creates PNG, JPEG, GIF, WebP, XPM, BMP images, among\
  \ other formats. \nGD is commonly used to generate charts, graphics, thumbnails,\
  \ and most anything else, on the fly. \nWhile not restricted to use on the web,\
  \ the most common applications of GD involve website development.\n            \n\
  http://libgd.bitbucket.org/\n\nRepository-Maintainer: Bjoern Gruening\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools/"
name: package_libgd_2_1
owner: iuc
type: tool_dependency_definition
