categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  12.135 of MCL.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The MCL algorithm is short for the Markov Cluster Algorithm, a\
  \ fast and scalable unsupervised cluster algorithm for graphs (also known as networks)\
  \ based on simulation of (stochastic) flow in graphs.\r\n\r\nhttp://micans.org/mcl/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_mcl_12_135
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
