categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.86 of the Berkley-DB libraries and binaries
long_description: |
  Berkeley DB (BDB) is a software library that provides a high-performance embedded database for key/value data.

  http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html
owner: iuc
name: package_berkeley_db_1_86
homepage_url: https://github.com/galaxyproject/tools-iuc/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_berkeley_1_86
type: tool_dependency_definition
