description: Contains a tool dependency definition that downloads version 0.1.5 of
  minced, a CRISPR finder.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "MinCED is a program to find Clustered Regularly Interspaced Short\
  \ Palindromic\nRepeats (CRISPRs) in full genomes or environmental datasets such\
  \ as metagenomes,\nin which sequence size can be anywhere from 100 to 800 bp. MinCED\
  \ runs from the\ncommand-line and was derived from CRT (http://www.room220.com/crt/):\n\
  \  Charles Bland et al., CRISPR Recognition Tool (CRT): a tool for automatic\n \
  \ detection of clustered regularly interspaced palindromic repeats, BMC\n  Bioinformatics\
  \ 8, no. 1 (2007): 209.\n\nRepository-Maintainer: Bjoern Gruening\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools/"
name: package_minced_0_1_5
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
