description: Contains a tool dependency definition that downloads and compiles version
  20131122 of GNU parallel.
long_description: "GNU parallel is a shell tool for executing jobs in parallel using\
  \ one or more computers. A job can be a single command or a small script that has\
  \ to be run for each of the lines in the input. The typical input is a list of files,\
  \ a list of hosts, a list of users, a list of URLs, or a list of tables. A job can\
  \ also be a command that reads from a pipe. GNU parallel can then split the input\
  \ and pipe it into commands in parallel. \r\n\r\nhttp://www.gnu.org/software/parallel/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening \r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_gnu_parallel_20131122
owner: iuc
type: tool_dependency_definition
