description: Contains a tool dependency definition that downloads and compiles version
  1.9 of the the python numpy package.
long_description: 'NumPy is the fundamental package for scientific computing with
  Python.


  This is the version 1.8 of numpy.

  www.numpy.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/galaxyproject/tools-iuc'
name: package_numpy_1_9
owner: iuc
type: tool_dependency_definition
