description: StringTie is a fast and highly efficient assembler of RNA-Seq alignments
  into potential transcripts.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "StringTie is a fast and highly efficient assembler of RNA-Seq alignments\
  \ into potential transcripts. It is primarily a genome-guided transcriptome assembler,\
  \ although it can borrow algorithmic techniques from de novo genome assembly to\
  \ help with transcript assembly. Its input can include not only the spliced read\
  \ alignments used by reference-based assemblers, but also longer contigs that were\
  \ assembled de novo from unambiguous, non-branching parts of a transcript. \r\n\r\
  \nhttp://ccb.jhu.edu/software/stringtie/\r\n\r\nRepository-Maintainer: Bjoern Gruening,\
  \ Dave Bouvier\r\nRepository-Development: https://github.com/galaxy-iuc/tool_shed/"
name: stringtie
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
