categories:
- Tool Dependency Packages
description: installs ucsc application gfServer for running a blat service
name: package_gfServer_35x1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
