categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and installs version
  0.4.19 of the JunctionSeq R library.
long_description: |
  The JunctionSeq R package is a powerful tool for testing differential junction usage
  (DJU) in next-generation, high-throughput RNA-Seq experiments.
  https://github.com/hartleys/JunctionSeq
name: package_junctionseq_0_4_19
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_junctionseq_0_4_19
type: tool_dependency_definition