categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.6 of Bioperl.
homepage_url: https://github.com/bgruening/galaxytools
long_description: "BioPerl is a toolkit of perl modules useful in building bioinformatics\
  \ solutions in Perl. It is built in an object-oriented manner so that many modules\
  \ depend on each other to achieve a task. \r\n\r\nhttp://www.bioperl.org\r\n\r\n\
  Repository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_bioperl_1_6
owner: iuc
remote_repository_url: https://github.com/bgruening/galaxytools
type: tool_dependency_definition
