description: Contains a tool dependency definition that downloads and compiles version
  1.6 of Bioperl.
long_description: "BioPerl is a toolkit of perl modules useful in building bioinformatics\
  \ solutions in Perl. It is built in an object-oriented manner so that many modules\
  \ depend on each other to achieve a task. \n\nhttp://www.bioperl.org\n\nRepository-Maintainer:\
  \ Bjoern Gruening\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_bioperl_1_6
owner: iuc
type: unrestricted
