categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.0.3 of the the R package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "This package is configured with the following options:\n\n./configure\
  \ --with-tcltk \\\n            --with-blas \\\n            --with-lapack \\\n  \
  \          --with-readline \\\n            --with-cairo \\\n            --with-libpng\
  \ \\\n            --without-x \\\n            --enable-R-shlib \\\n            --disable-R-framework\
  \ \\\n            --libdir=$INSTALL_DIR/lib \\\n            --prefix=$INSTALL_DIR"
name: package_r_3_1_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
