description: Contains a tool dependency definition that downloads and compiles version
  3.0.3 of the the R package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "This package is configured with the following options:\r\n\r\n\
  ./configure --with-tcltk \\\r\n            --with-blas \\\r\n            --with-lapack\
  \ \\\r\n            --with-readline \\\r\n            --with-cairo \\\r\n      \
  \      --with-libpng \\\r\n            --without-x \\\r\n            --enable-R-shlib\
  \ \\\r\n            --disable-R-framework \\\r\n            --libdir=$INSTALL_DIR/lib\
  \ \\\r\n            --prefix=$INSTALL_DIR"
name: package_r_3_1_2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
