description: 'MUMmer is a system for rapidly aligning entire genomes '
long_description: This Galaxy ToolShed package downloads and installs the MUMmer package,
  for use by other Galaxy tools/wrappers.
name: package_mummer_3_23
owner: iuc
type: tool_dependency_definition
