description: 'MUMmer is a system for rapidly aligning entire genomes '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: This Galaxy ToolShed package downloads and installs the MUMmer package,
  for use by other Galaxy tools/wrappers.
name: package_mummer_3_23
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
