description: ' Contains a tool dependency definition that downloads the binary version
  22.4 of tbl2asn. '
long_description: "tbl2asn is an automated bulk submission program\r\n\r\ntbl2asn\
  \ is a program that automates the submission of sequence records to\r\nGenBank.\
  \  It uses many of the same functions as Sequin, but is driven\r\nentirely by data\
  \ files, and records need no additional manual editing before\r\nsubmission.  Entire\
  \ genomes, consisting of many chromosomes with feature\r\nannotation, can be processed\
  \ in seconds using this method.\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\n\
  Repository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies/package_tbl2asn_22_4"
name: package_tbl2asn_22_4
owner: iuc
type: tool_dependency_definition
