categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads version 1.0 of genomeGTFtools
homepage_url: https://github.com/Eduardo-Alves/genomeGTFtools
long_description: scripts to convert various features and annotations into a GFF-like file for use in genome browsers
name: package_genomegtftools_1_0
owner: planemo
