categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.9.x of the python library dill.
long_description: 'Dill extends python''s ''pickle'' module for serializing and de-serializing

  python objects to the majority of the built-in python types. Serialization

  is the process of converting an object to a byte stream, and the inverse of

  which is converting a byte stream back to on python object hierarchy.

  http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill

  '
name: package_dill_0.2
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
