categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.7 of Python Pillow library.
name: package_python_pillow_2_7
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc
type: tool_dependency_definition
