owner: iuc
name: package_snpeff_4_0
type: tool_dependency_definition
description: Contains a tool dependency definition that installs version 4.0 SnpEff,
  a variant annotation and effect prediction tool.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    SnpEff is a variant annotation and effect prediction tool by Pablo
    Cingolani.

    It annotates and predicts the effects of variants on genes (such as amino
    acid changes).

    SnpEff and SnpSift (http://snpeff.sourceforge.net/)
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
