---
name: bcftools
owner: iuc
description: bcftools wrappers
long_description: |
    https://samtools.github.io/bcftools/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/bcftools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for bcftools application {{ tool_name }}."
suite:
  name: "suite_bcftools_1_2"
  description: "A suite of Galaxy tools designed to work with version 1.2 of the bcftools package."
  long_description: |
      https://samtools.github.io/bcftools/
exclude:
    - convert.py
    - help/help_annotate.txt
    - help/help_call.txt
    - help/help_concat.txt
    - help/help_consensus.txt
    - help/help_convert.txt
    - help/help_filter.txt
    - help/help_gtcheck.txt
    - help/help_isec.txt
    - help/help_merge.txt
    - help/help_norm.txt
    - help/help_plugin.txt
    - help/help_query.txt
    - help/help_reheader.txt
    - help/help_roh.txt
    - help/help_stats.txt
    - help/help_view.txt
