categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.1.44 of the python library reportlab.
long_description: |
  reportlab

name: package_python_2_7_reportlab_3_1_44
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_python_2_7_reportlab_3_1_44
type: tool_dependency_definition
