categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.0.17 of DESeq2.
long_description: ''
name: package_deseq2_1_0_17
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
