description: Contains a tool dependency definition that downloads and compiles version
  1.0.17 of the the DESeq2 package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Differential gene expression analysis based on the negative binomial\
  \ distribution.\r\nhttp://www.bioconductor.org/packages/2.12/bioc/html/DESeq2.html\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_deseq2_1_0_17
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
