description: Contains a tool dependency definition that downloads and compiles version
  1.4.x of the the python matplotlib package.
long_description: 'matplotlib is a python 2D plotting library which produces publication
  quality figures.


  This is the version 1.2.x of matplotlib.

  www.matplotlib.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/galaxyproject/tools-iuc'
name: package_matplotlib_1_4
owner: iuc
type: tool_dependency_definition
