description: stringtie
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: ''
name: package_stringtie_0_97
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
