categories:
- Tool Dependency Packages
description: stringtie
name: package_stringtie_0_97
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_stringtie_0_97
type: tool_dependency_definition
