# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_express_1_5_1
owner: iuc
name: package_express_1_5_1
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  1.5.1 of the eXpress package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    eXpress is a streaming tool for quantifying the abundances of a set of
    target sequences from sampled subsequences. Example applications include
    transcript-level RNA-Seq quantification, allele-specific/haplotype
    expression analysis (from RNA-Seq), transcription factor binding
    quantification in ChIP-Seq, and analysis of metagenomic data.

    http://bio.math.berkeley.edu/eXpress/overview.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
