categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and installs 2004_02_13 snapshot of PredSi
homepage_url: http://www.predisi.de/ 
long_description: PREDIction of SIgnal peptides
name: package_predsi_2004_02_13
owner: iuc
