description: ' Contains a tool dependency definition that downloads and compiles version
  3.8.31 of MUSCLE.'
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "MUSCLE is one of the best-performing multiple alignment programs\
  \ according to published benchmark tests.\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_muscle_3_8_31
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
