categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.1.19 of the SAMTools package
long_description: 'Utilities for the Sequence Alignment/Map (SAM) format

  Program: samtools (Tools for alignments in the SAM format)

  Version: 0.1.19

  '
name: package_samtools_0_1_19
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
