description: Contains a tool dependency definition that downloads and compiles version
  0.1.19 of the SAMTools package
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Utilities for the Sequence Alignment/Map (SAM) format\r\n\r\nProgram:\
  \ samtools (Tools for alignments in the SAM format)\r\nVersion: 0.1.19\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_samtools_0_1_19
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
