categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.1.5 of libyaml.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "LibYAML is a YAML 1.1 parser and emitter written in C. \r\n\r\n\
  http://pyyaml.org/wiki/LibYAML\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\n\
  Repository-Development: https://github.com/bgruening/galaxytools"
name: package_libyaml_0_1_5
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
