description: Contains a tool dependency definition that downloads and compiles version
  0.1.5 of libyaml.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "LibYAML is a YAML 1.1 parser and emitter written in C. \n\nhttp://pyyaml.org/wiki/LibYAML\n\
  \nRepository-Maintainer: Bjoern Gruening\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_libyaml_0_1_5
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
