categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.2.8 of the the zlib library.
long_description: |
  A Massively Spiffy Yet Delicately Unobtrusive Compression Library

  http://www.zlib.net/
name: package_zlib_1_2_8
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
