description: Contains a tool dependency definition that downloads and compiles version
  1.2.8 of the the zlib library.
long_description: "A Massively Spiffy Yet Delicately Unobtrusive Compression Library\
  \ \r\n\r\nhttp://www.zlib.net/ \r\n\r\nRepository-Maintainer: Bjoern Gruening \r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_zlib_1_2_8
owner: iuc
type: tool_dependency_definition
