# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_r_3_1_1
owner: iuc
name: package_r_3_1_1
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version
  3.1.1 of the R package.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "R is a free software environment for statistical computing and\
  \ graphics.\r\nhttp://www.r-project.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
