categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.9g of the squid library.
homepage_url: https://github.com/bgruening/galaxytools
long_description: "SQUID is a freely redistributable library of C code functions for\r\
  \nsequence analysis. SQUID also includes a number of small utility\r\nprograms.\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening & Cameron Smith\r\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools"
name: package_squid_1_9g
owner: iuc
remote_repository_url: https://github.com/bgruening/galaxytools
type: tool_dependency_definition
