description: Contains a tool dependency definition that downloads and compiles version
  1.9g of the squid library.
long_description: 'SQUID is a freely redistributable library of C code functions for

  sequence analysis. SQUID also includes a number of small utility

  programs.


  Repository-Maintainer: Bjoern Gruening & Cameron Smith

  Repository-Development: https://github.com/bgruening/galaxytools'
name: package_squid_1_9g
owner: iuc
type: tool_dependency_definition
