categories:
- Tool Dependency Packages
description: seqtk package
homepage_url: ''
long_description: seqtk package
name: package_seqtk_1_0_r75
owner: iuc
remote_repository_url: ''
type: tool_dependency_definition
