categories:
- Tool Dependency Packages
description: seqtk package
long_description: |
  Sequence Toolkit is a suite of utilities to work with FastA and FastQ data
name: package_seqtk_1_0_r75
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
