description: Contains a tool dependency definition that downloads and compiles version
  1.0-r75 of seqtk
long_description: "Seqtk is a fast and lightweight tool for processing sequences in\
  \ the FASTA or FASTQ format. It seamlessly parses both FASTA and FASTQ files which\
  \ can also be optionally compressed by gzip.\r\n\r\nhttps://github.com/lh3/seqtk/\r\
  \n\r\nRepository-Maintainer: Eric Rasche\r\nRepository-Development: https://github.com/galaxyproject/tools-iuc/"
name: package_seqtk_1_0_r75
owner: iuc
type: tool_dependency_definition
