description: Contains a tool dependency definition that downloads and extract version
  2.0.x of the the eigen template library.
long_description: "Eigen is a C++ template library for linear algebra: matrices, vectors,\
  \ numerical solvers, and related algorithms.\r\n\r\nhttp://eigen.tuxfamily.org/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_eigen_2_0
owner: iuc
type: tool_dependency_definition
