categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and extract version
  2.0.x of the the eigen template library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: 'Eigen is a C++ template library for linear algebra: matrices, vectors,
  numerical solvers, and related algorithms.'
name: package_eigen_2_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
