categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.9.x of the python library networkx.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "NetworkX is a Python language software package for the creation,\
  \ manipulation, and study of the structure, dynamics, and functions of complex networks.\r\
  \n\r\nhttp://networkx.github.io/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/galaxy-iuc/tool_shed/"
name: package_networkx_1_9
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
