description: Contains a tool dependency definition that downloads and compiles version
  1.9.x of the python library networkx.
long_description: 'NetworkX is a Python language software package for the creation,
  manipulation, and study of the structure, dynamics, and functions of complex networks.


  http://networkx.github.io/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/galaxy-iuc/tool_shed/'
name: package_networkx_1_9
owner: iuc
type: tool_dependency_definition
