# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_rpy2_2_3_6
owner: iuc
name: package_rpy2_2_3_6
type: tool_dependency_definition
description: Provides RPy2 2.3.6
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    rpy2 is a redesign and rewrite of rpy. It is providing a low-level
    interface to R from Python, a proposed high-level interface, including
    wrappers to graphical libraries, as well as R-like structures and
    functions.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
