categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.7 of Python reportlab library.
name: package_python_reportlab_3_1_44
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc
type: tool_dependency_definition
