description: ' Contains a tool dependency definition that downloads and compiles version
  2.14 of the GNU grep. '
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The grep command searches one or more input files for lines containing\
  \ a match to a specified pattern.\r\n\r\nhttp://www.gnu.org/software/grep/\r\n\r\
  \nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_gnu_grep_2_14
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
