categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.1.0 of the R interpreter.
long_description: 'R is a free software environment for statistical computing and
  graphics.

  http://www.r-project.org/

  This package is configured with the following options:

  ./configure --with-tcltk \

  --with-blas \

  --with-lapack \

  --with-readline \

  --with-cairo \

  --with-libpng \

  --without-x \

  --enable-R-shlib \

  --disable-R-framework \

  --libdir=$INSTALL_DIR/lib \

  --prefix=$INSTALL_DIR

  '
name: package_r_3_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
