categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.1.0 of the R interpreter.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "R is a free software environment for statistical computing and\
  \ graphics.\r\nhttp://www.r-project.org/\r\n\r\nThis package is configured with\
  \ the following options:\r\n\r\n./configure --with-tcltk \\\r\n            --with-blas\
  \ \\\r\n            --with-lapack \\\r\n            --with-readline \\\r\n     \
  \       --with-cairo \\\r\n            --with-libpng \\\r\n            --without-x\
  \ \\\r\n            --enable-R-shlib \\\r\n            --disable-R-framework \\\r\
  \n            --libdir=$INSTALL_DIR/lib \\\r\n            --prefix=$INSTALL_DIR\
  \  \r\n\r\nRepository-Maintainer: Dave Bouvier\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_r_3_1_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
