description: Downloads and compiles version 4.6.3 of the Trans-Proteomic Pipeline.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The Trans-Proteomic Pipeline (TPP) is a collection of integrated\
  \ tools for MS/MS proteomics, developed at the SPC.  \r\n\r\nhttp://tools.proteomecenter.org\
  \ \r\n\r\nRepository-Maintainer: RNA-Team (Bjoern Gruening, Pavan Videm) \r\nRepository-Development:\
  \ https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_tpp_4_6_3
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
