owner: iuc
name: package_tpp_4_6_3
description: Downloads and compiles version 4.6.3 of the Trans-Proteomic Pipeline.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    The Trans-Proteomic Pipeline (TPP) is a collection of integrated tools for
    MS/MS proteomics, developed at the SPC. 
    
    http://tools.proteomecenter.org
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
