categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.42.9 of e2fsprogs.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "It provides the filesystem utilities for use with the ext2 filesystem.\
  \ It also supports the ext3 and ext4 filesystems.\r\n\r\nhttp://e2fsprogs.sourceforge.net/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools\r\
  \n"
name: package_e2fsprogs_1_42_9
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
