categories:
- Data Managers
description: bwa-meth is a fasta and accurate aligner for BS-seq data.
long_description: |
 A fast and accurate aligner of BS-seq data.
 - Supports single-end and paired-end alignments
 - Supports gapped alignments
 - Faster and more sensitive than many other tools
name: data_manager_bwameth_index_builder
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/data_managers/data_manager_bwameth_index_builder
type: unrestricted
