categories:
- Tool Dependency Packages
description: 'Tabix: Generic indexer for TAB-delimited genome position files + bgzip'
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Tabix indexes a TAB-delimited genome position file in.tab.bgz and\
  \ creates an index file in.tab.bgz.tbi when region is absent from the command-line.\
  \ The input data file must be position sorted and compressed by bgzip which has\
  \ a gzip(1) like interface. After indexing, \ntabix is able to quickly retrieve\
  \ data lines overlapping regions specified in the format \"chr:beginPos-endPos\"\
  . Fast data retrieval also works over network if URI is given as a file name and\
  \ in this case the index file will be downloaded if it is not present locally. \n\
  \nhttp://samtools.sourceforge.net/tabix.shtml\n\nRepository-Maintainer: Bjoern Gruening\n\
  Repository-Development: https://github.com/bgruening/galaxytools"
name: package_tabix_0_2_6
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
