categories:
- Tool Dependency Packages
description: Automatically Tuned Linear Algebra Software
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "The ATLAS (Automatically Tuned Linear Algebra Software) project\
  \ is an ongoing research effort focusing on applying empirical techniques in order\
  \ to provide portable performance. At present, it provides C and Fortran77 interfaces\
  \ to a portably efficient BLAS implementation, as well as a few routines from LAPACK.\r\
  \n\r\nhttp://math-atlas.sourceforge.net/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/"
name: package_atlas_3_11
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
