description: Contains a tool dependency definition that downloads and compiles libncurses
  5.9.
long_description: "ncurses (new curses) is a programming library that provides an\
  \ API which allows the programmer to write text-based user interfaces in a terminal-independent\
  \ manner\r\n\r\nhttp://www.gnu.org/software/ncurses/\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_ncurses_5_9
owner: iuc
type: tool_dependency_definition
