description: 'updated version of the tool factory '
long_description: Includes arbitrary parameters and multiple inputs. Cost is more
  complex parameter parsing but examples are provided. Now allows selecting any installed
  interpreter tool shed package or using the system default!
name: tool_factory_2
owner: fubar
type: unrestricted
