owner: fubar
name: tool_factory_2
description: Galaxy Tool Factory v2
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Includes arbitrary parameters and multiple inputs. Cost is more complex
    parameter parsing but examples are provided. Now allows selecting any
    installed interpreter tool shed package or using the system default!
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
categories:
- Tool Generators
