# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_faToTwoBit_35x1
owner: iuc
name: package_faToTwoBit_35x1
type: tool_dependency_definition
description: installs ucsc applications: faToTwoBit for running a blat service
homepage_url: https://github.com/galaxyproject/tools-iuc/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
