categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.14 of the python library pandas.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Pandas is an open source, BSD-licensed library providing high-performance,\
  \ easy-to-use data structures and data analysis tools for the Python programming\
  \ language.\r\n\r\nhttp://pandas.pydata.org/\r\n\r\nRepository-Maintainer: Bjoern\
  \ Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/\r\
  \n"
name: package_pandas_0_14
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
