description: Contains a tool dependency definition that downloads and compiles version
  0.14 of the python library pandas.
long_description: 'Pandas is an open source, BSD-licensed library providing high-performance,
  easy-to-use data structures and data analysis tools for the Python programming language.


  http://pandas.pydata.org/


  Repository-Maintainer: Bjoern Gruening

  Repository-Development: https://github.com/bgruening/galaxytools/

  '
name: package_pandas_0_14
owner: iuc
type: tool_dependency_definition
