categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  5.1.x of the the Qt library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Qt is a cross-platform application and UI framework for developers\
  \ using C++ or QML, a CSS & JavaScript like language. Qt Creator is the supporting\
  \ Qt IDE.\r\n\r\nhttp://qt-project.org/\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_qt_5_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
