# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_eden_1_3
owner: iuc
name: package_eden_1_3
type: tool_dependency_definition
description: Contains a tool dependency definition that downloads and compiles version 1.3.x of the EDeN package. 
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    The Neighborhood Subgraph Pairwise Distance Kernel can be used to induce an
    explicit feature representation for graphs. This in turn allows fast
    stochastic gradient descent methods to be applied for classification tasks. 

    EDeN is developed by Fabrizio Costa.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
