description: Contains a tool dependency definition that downloads and installs version
  2.8.2 of the cummeRbund R library.
long_description: Allows for persistent storage, access, exploration, and manipulation
  of Cufflinks high-throughput sequencing data. In addition, provides numerous plotting
  functions for commonly used visualizations.
name: package_cummerbund_2_8_2
owner: iuc
type: tool_dependency_definition
