owner: iuc
name: package_cummerbund_2_8_2
description: Contains a tool dependency definition that downloads and installs version
  2.8.2 of the cummeRbund R library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Allows for persistent storage, access, exploration, and manipulation of
    Cufflinks high-throughput sequencing data. In addition, provides numerous
    plotting functions for commonly used visualizations.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
categories:
- Tool Dependency Packages
