categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles all
  dependencies from the Perl XML::Parser::Expat library.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "XML::Parser - A perl module for parsing XML documents\r\n\r\nhttp://search.cpan.org/~toddr/XML-Parser-2.41/Parser.pm\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/galaxyproject/tools-iuc"
name: package_perl_xml_parser_expat_2_41
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
