# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_protk_1_2_4
owner: iuc
name: package_protk_1_2_4
type: tool_dependency_definition
description: Ruby Proteomics Toolkit 1.2.4
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    Protk is a suite of tools for proteomics. It aims to present a simple and
    consistent command-line interface across otherwise disparate third party
    tools. The following analysis tasks are currently supported;

    * Tandem MS search with X!Tandem, Mascot, OMSSA and MS-GF+
    * Peptide and Protein inference with Peptide Prophet, iProphet and Protein Prophet
    * Conversion of pepXML or protXML to tabulular format
    * Proteogenomics (mapping peptides to genomic coordinates)

    https://github.com/iracooke/protk
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
