categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that installs version 0.02 of Set-IntervalTree.
long_description: |
   Set::IntervalTree - Perform range-based lookups on sets of ranges.

   http://search.cpan.org/~benbooth/Set-IntervalTree-0.02/lib/Set/IntervalTree.pm
name: package_perl_set_intervaltree_0_02
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_perl_set_intervaltree_0_02
type: tool_dependency_definition
