description: Contains a tool dependency definition that downloads and compiles version
  2.22 of bedtools.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "bedtools - a swiss army knife for genome arithmetic\r\n\r\nRepository-Maintainer:\
  \ Bjoern Gruening\r\nRepository-Development: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_bedtools_2_22"
name: package_bedtools_2_22
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
