categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and installs version 3.0.2 of PSORTb
homepage_url: http://www.psort.org/psortb/
long_description: PSORTb version 3.0.2 bacterial localization prediction tool
name: package_psortb_3_0
owner: iuc
