categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  2.60 of the prodigal genefinding algorithm.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "Prodigal (Prokaryotic Dynamic Programming Genefinding Algorithm)\
  \ is a microbial (bacterial and archaeal) gene finding program developed at Oak\
  \ Ridge National Laboratory and the University of Tennessee.\r\n\r\nhttp://prodigal.ornl.gov/\r\
  \n\r\nRepository-Maintainer: Bjoern Gruening\r\nRepository-Development: https://github.com/bgruening/galaxytools/tree/master/orphan_tool_dependencies"
name: package_prodigal_2_60
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: unrestricted
