categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles verions
  6.0 of unzip.
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: "UnZip is an extraction utility for archives compressed in .zip\
  \ format (also called \"zipfiles\"). Although highly compatible both with PKWARE's\
  \ PKZIP and PKUNZIP utilities for MS-DOS and with Info-ZIP's own Zip program, our\
  \ primary objectives have been portability and non-MSDOS functionality. \r\n\r\n\
  http://www.info-zip.org/UnZip.html\r\n\r\nRepository-Maintainer: Bjoern Gruening\r\
  \nRepository-Development: https://github.com/bgruening/galaxytools"
name: package_unzip_6_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
type: tool_dependency_definition
