name: package_anaconda_2_3_0
owner: iuc
description: |
  Contains a tool dependency definition that downloads and installs Anaconda version 2.3.0
homepage_url: https://www.continuum.io
long_description: |
  This installation recipe installs the Anaconda version 2.3.0 of the Python programming language
  version 2.7.10.  Anaconda is a completely free Python distribution (including for commercial use
  and redistribution). It includes more than 300 of the most popular Python packages for science,
  math, engineering, and data analysis.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_anaconda_2_3_0
type: tool_dependency_definition
categories:
- Tool Dependency Packages
