categories: [Tool Dependency Packages]
description: Contains a tool dependency definition that downloads and compiles version 1.3 of ariadne
homepage_url: http://www.well.ox.ac.uk/rmott/ARIADNE/
long_description: ARIADNE is a package of two programs, ariadne and prospero, that compare protein sequences and profiles using the Smith-Waterman algorithm
name: package_ariadne_1_3
owner: planemo
