# repository published to https://toolshed.g2.bx.psu.edu/repos/iuc/package_libsvm_3_16
owner: iuc
name: package_libsvm_3_16
type: tool_dependency_definition
description: Package providing LibSVM 3.16
homepage_url: https://github.com/galaxyproject/tools-iuc/
long_description: |
    LIBSVM is an integrated software for support vector classification, (C-SVC,
    nu-SVC), regression (epsilon-SVR, nu-SVR) and distribution estimation
    (one-class SVM). It supports multi-class classification.

    http://www.csie.ntu.edu.tw/~cjlin/libsvm/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/
categories:
- Tool Dependency Packages
